# Generated by Django 2.2 on 2021-03-08 11:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0001_initial_squashed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='sender_id',
        ),
        migrations.RemoveField(
            model_name='flaggedmessage',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='flaggedmessage',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='flaggedmessage',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='individual',
        ),
        migrations.AddField(
            model_name='chat',
            name='messages_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='participant_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chat',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flaggedmessage',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='gender',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='messages_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='individual',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='study_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='from_group',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='room_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.TextField(default='Nil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='telegram_msg_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flaggedmessage',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mpact.Message'),
        ),
        migrations.CreateModel(
            name='UserChatUnread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('room_id', models.IntegerField()),
                ('unread_count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('user_id', 'room_id')},
            },
        ),
    ]
