# Generated by Django 2.2 on 2021-02-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0001_initial_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='age',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='gender',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='study_id',
            field=models.TextField(null=True),
        ),
    ]
