# Generated by Django 2.2 on 2020-12-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=350)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
