# Generated by Django 2.2 on 2020-12-21 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0002_chatdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=350)),
                ('first_name', models.CharField(max_length=350)),
                ('last_name', models.CharField(max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('title', models.CharField(max_length=350)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=350, null=True)),
                ('first_name', models.CharField(max_length=350)),
                ('last_name', models.CharField(max_length=350)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='mpact.Bot')),
            ],
        ),
        migrations.DeleteModel(
            name='ChatData',
        ),
        migrations.AddField(
            model_name='bot',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mpact.Chat'),
        ),
    ]
