# Generated by Django 2.2 on 2021-02-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0002_auto_20210201_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedmessage',
            name='is_group',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
