# Generated by Django 2.2 on 2020-12-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0003_auto_20201221_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='individual_id',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='bot',
            constraint=models.UniqueConstraint(fields=('chat', 'bot_id'), name='unique_chat_bot'),
        ),
        migrations.AddConstraint(
            model_name='individual',
            constraint=models.UniqueConstraint(fields=('bot', 'individual_id'), name='unique_bot_individuals'),
        ),
    ]
