# Generated by Django 2.2 on 2021-02-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0003_flaggedmessage_is_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
