# Generated by Django 2.2 on 2021-02-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0004_message_is_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedmessage',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
    ]
