# Generated by Django 2.2 on 2020-12-24 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0005_auto_20201224_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='bot',
            name='unique_chat_bot',
        ),
        migrations.RemoveConstraint(
            model_name='individual',
            name='unique_bot_individuals',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='bot_id',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='individual_id',
        ),
        migrations.AlterField(
            model_name='bot',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bot',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bot',
            name='last_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='username',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='individual',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='individual',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='individual',
            name='last_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='individual',
            name='username',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpact.Bot'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpact.Chat'),
        ),
        migrations.AddField(
            model_name='botindividual',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpact.Bot'),
        ),
        migrations.AddField(
            model_name='botindividual',
            name='individual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpact.Individual'),
        ),
        migrations.AddField(
            model_name='bot',
            name='chats',
            field=models.ManyToManyField(through='mpact.ChatBot', to='mpact.Chat'),
        ),
        migrations.AddField(
            model_name='individual',
            name='bots',
            field=models.ManyToManyField(through='mpact.BotIndividual', to='mpact.Bot'),
        ),
    ]
