# Generated by Django 2.2 on 2021-01-05 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0006_auto_20201224_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botindividual',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_individuals', to='mpact.Bot'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='last_name',
            field=models.TextField(null=True),
        ),
    ]
