# Generated by Django 2.2 on 2021-02-19 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0006_auto_20210208_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chat',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
