# Generated by Django 2.2 on 2021-01-06 16:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0007_auto_20210105_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField()),
                ('message', models.TextField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpact.Individual')),
            ],
        ),
    ]
