# Generated by Django 2.2 on 2021-02-24 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0007_auto_20210219_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='sender_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='individual',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_flagged',
        ),
        migrations.AddField(
            model_name='message',
            name='from_group',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='room_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.TextField(default='Nil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='telegram_msg_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flaggedmessage',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mpact.Message'),
        ),
        migrations.AlterUniqueTogether(
            name='flaggedmessage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='flaggedmessage',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='flaggedmessage',
            name='is_group',
        ),
        migrations.RemoveField(
            model_name='flaggedmessage',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='flaggedmessage',
            name='room_id',
        ),
    ]
