# Generated by Django 2.2 on 2021-03-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0008_auto_20210224_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='messages_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='participant_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='individual',
            name='messages_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='individual',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
