# Generated by Django 2.2 on 2021-01-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpact", "0008_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="individual",
            name="access_hash",
            field=models.TextField(default="Null"),
            preserve_default=False,
        ),
    ]
