# Generated by Django 2.2 on 2021-01-22 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0010_customperiodictask'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
                ('first_name', models.TextField(null=True)),
                ('message', models.TextField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='customperiodictask',
            name='message',
            field=models.TextField(blank=True, help_text='Enter the Message', verbose_name='Message'),
        ),
    ]
