# Generated by Django 2.2 on 2021-01-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0011_auto_20210122_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedmessage',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flaggedmessage',
            name='message',
            field=models.TextField(),
        ),
    ]
