# Generated by Django 2.2 on 2020-11-05 14:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatData',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('type', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('all_members_are_administrators', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_bot', models.BooleanField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('language_code', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpact.UserData')),
            ],
        ),
    ]
