# Generated by Django 2.2 on 2020-11-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpact', '0002_auto_20201112_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchat',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
